spring.application.name=TaskManager
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager__db
spring.datasource.username=postgres
spring.datasource.password=${nabin99}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect